#!/usr/bin/env node
/**
 * Flxify build script
 *
 * Reads lib modules from scripts/lib/ and scripts from scripts/.
 * Generates a fully self-contained app.js that works offline and with file:// URLs.
 * No `new Function()` or `eval()` in generated output — CSP-compatible.
 *
 * Usage: node build_app.js
 */

const fs = require('fs');
const path = require('path');

const SCRIPTS_DIR = path.join(__dirname, 'scripts');
const LIB_DIR = path.join(SCRIPTS_DIR, 'lib');
const OUTPUT = path.join(__dirname, 'app.js');

// ---- Auto-discover lib modules ----
const libFiles = fs.readdirSync(LIB_DIR)
  .filter(f => f.endsWith('.js'))
  .sort();

// ---- Auto-discover scripts ----
const scriptFiles = fs.readdirSync(SCRIPTS_DIR)
  .filter(f => f.endsWith('.js'))
  .sort();

// ---- Parse script metadata at build time ----
function parseMetadata(source, filename) {
  const metaMatch = source.match(/\/\*\*([\s\S]*?)\*\*\//);
  if (!metaMatch) {
    console.warn(`  WARNING: No metadata block in ${filename}, skipping`);
    return null;
  }
  const cleanedJson = metaMatch[1].trim().replace(/,\s*([\]}])/g, '$1');
  try {
    return JSON.parse(cleanedJson);
  } catch (e) {
    console.warn(`  WARNING: Invalid metadata JSON in ${filename}: ${e.message}`);
    return null;
  }
}

// ---- Read and validate all scripts ----
const scriptEntries = [];
for (const file of scriptFiles) {
  const source = fs.readFileSync(path.join(SCRIPTS_DIR, file), 'utf-8');
  const metadata = parseMetadata(source, file);
  if (!metadata) continue;
  scriptEntries.push({ file, source, metadata });
}

// ---- Read lib modules ----
const libEntries = [];
for (const file of libFiles) {
  const source = fs.readFileSync(path.join(LIB_DIR, file), 'utf-8');
  const name = file.replace(/\.js$/, '');
  libEntries.push({ file, name, source });
}

console.log(`Found ${libEntries.length} lib modules and ${scriptEntries.length} scripts.`);

// ---- Generate app.js ----
let output = `// Flxify - app.js
// Generated by build_app.js - do not edit directly.
// Edit scripts in scripts/ then run: node build_app.js

(function() {

// ============================================================
// 1. Module System (require shim)
// ============================================================

var flxifyModules = {};

function require(modulePath) {
  if (typeof modulePath === 'string' && modulePath.startsWith('@flxify/')) {
    var name = modulePath.replace('@flxify/', '').replace('.js', '');
    if (flxifyModules[name]) return flxifyModules[name];
    console.warn('Module not found: ' + name);
  }
  return null;
}

// ============================================================
// 2. Lib Modules (inlined at build time)
// ============================================================

`;

// Generate each lib module as direct code (no new Function)
for (const lib of libEntries) {
  output += `// --- ${lib.name} ---\n`;
  output += `(function() {\n`;
  output += `  var module = { exports: {} };\n`;
  output += `  var exports = module.exports;\n`;
  output += `  (function(exports, module) {\n`;
  output += lib.source;
  output += `\n  }).call(module.exports, module.exports, module);\n`;
  output += `  flxifyModules[${JSON.stringify(lib.name)}] = module.exports;\n`;
  output += `})();\n\n`;
}

output += `
// ============================================================
// 3. Script Registry (pre-compiled at build time)
// ============================================================

var scripts = [];

`;

// Generate each script as a pre-compiled object with execute function
for (const entry of scriptEntries) {
  const m = entry.metadata;
  output += `scripts.push({\n`;
  output += `  name: ${JSON.stringify(m.name || 'Unnamed')},\n`;
  output += `  description: ${JSON.stringify(m.description || '')},\n`;
  output += `  author: ${JSON.stringify(m.author || '')},\n`;
  output += `  icon: ${JSON.stringify(m.icon || '')},\n`;
  output += `  tags: ${JSON.stringify(m.tags || '')},\n`;
  output += `  execute: function(require, state) {\n`;
  output += entry.source;
  output += `\n    if (typeof main === "function") main(state);\n`;
  output += `  }\n`;
  output += `});\n\n`;
}

output += `scripts.sort(function(a, b) { return a.name.localeCompare(b.name); });

// ============================================================
// 4. Toast System
// ============================================================

function showToast(message, type) {
  var container = document.getElementById('toast');
  var el = document.createElement('div');
  el.className = 'toast-message ' + (type || 'info');
  el.textContent = message;
  container.appendChild(el);
  setTimeout(function() {
    if (el.parentNode) el.parentNode.removeChild(el);
  }, 3000);
}

// ============================================================
// 5. BoopState Class
// ============================================================

function BoopState(fullText, selectionStart, selectionEnd) {
  this._fullText = fullText;
  this._selectionStart = selectionStart;
  this._selectionEnd = selectionEnd;
  this._selection = (selectionStart !== selectionEnd)
    ? fullText.substring(selectionStart, selectionEnd)
    : null;
  this._isSelection = this._selection !== null;
  this._insertText = null;
}

Object.defineProperty(BoopState.prototype, 'fullText', {
  get: function() { return this._fullText; },
  set: function(val) { this._fullText = val; }
});

Object.defineProperty(BoopState.prototype, 'selection', {
  get: function() { return this._selection; },
  set: function(val) { this._selection = val; }
});

Object.defineProperty(BoopState.prototype, 'isSelection', {
  get: function() { return this._isSelection; }
});

Object.defineProperty(BoopState.prototype, 'text', {
  get: function() {
    return this._isSelection ? this._selection : this._fullText;
  },
  set: function(val) {
    if (this._isSelection) {
      this._selection = val;
    } else {
      this._fullText = val;
    }
  }
});

BoopState.prototype.postError = function(msg) { showToast(msg, 'error'); };
BoopState.prototype.postInfo = function(msg) { showToast(msg, 'info'); };
BoopState.prototype.insert = function(text) { this._insertText = text; };

// ============================================================
// 6. Script Executor
// ============================================================

function executeScript(script) {
  var cm = window.cmEditor;
  var fullText = cm.state.doc.toString();
  var selFrom = cm.state.selection.main.from;
  var selTo = cm.state.selection.main.to;
  var state = new BoopState(fullText, selFrom, selTo);

  try {
    script.execute(require, state);
  } catch (e) {
    showToast('Error: ' + e.message, 'error');
    console.error('Script execution error:', e);
    return;
  }

  // Apply results back to CodeMirror editor
  if (state._insertText !== null) {
    cm.dispatch({
      changes: { from: selFrom, to: selTo, insert: state._insertText },
      selection: { anchor: selFrom + state._insertText.length }
    });
  } else if (state._isSelection && state._selection !== null) {
    cm.dispatch({
      changes: { from: state._selectionStart, to: state._selectionEnd, insert: state._selection },
      selection: { anchor: state._selectionStart, head: state._selectionStart + state._selection.length }
    });
  } else {
    cm.dispatch({
      changes: { from: 0, to: cm.state.doc.length, insert: state._fullText }
    });
  }
}

// ============================================================
// 7. Command Palette
// ============================================================

var palette = document.getElementById('command-palette');
var searchInput = document.getElementById('search');
var resultsList = document.getElementById('results');
var activeIndex = 0;
var filteredScripts = [];

function showPalette() {
  palette.classList.remove('hidden');
  searchInput.value = '';
  filterScripts('');
  searchInput.focus();
}

function hidePalette() {
  palette.classList.add('hidden');
  if (window.cmEditor) window.cmEditor.focus();
}

function togglePalette() {
  if (palette.classList.contains('hidden')) {
    showPalette();
  } else {
    hidePalette();
  }
}

function fuzzyScore(query, text) {
  if (!query) return 1;
  var lowerQuery = query.toLowerCase();
  var lowerText = text.toLowerCase();

  if (lowerText === lowerQuery) return 100;
  if (lowerText.startsWith(lowerQuery)) return 80;
  if (lowerText.includes(lowerQuery)) return 60;

  var qi = 0;
  var consecutive = 0;
  var maxConsecutive = 0;
  var matched = 0;
  for (var ti = 0; ti < lowerText.length && qi < lowerQuery.length; ti++) {
    if (lowerText[ti] === lowerQuery[qi]) {
      qi++;
      matched++;
      consecutive++;
      if (consecutive > maxConsecutive) maxConsecutive = consecutive;
    } else {
      consecutive = 0;
    }
  }
  if (qi < lowerQuery.length) return 0;
  return 20 + maxConsecutive * 5 + matched;
}

function filterScripts(query) {
  if (!query) {
    filteredScripts = scripts.slice();
  } else {
    var scored = scripts.map(function(s) {
      var nameScore = fuzzyScore(query, s.name) * 0.9;
      var tagScore = fuzzyScore(query, s.tags) * 0.6;
      var descScore = fuzzyScore(query, s.description) * 0.2;
      var score = Math.max(nameScore, tagScore, descScore);
      return { script: s, score: score };
    }).filter(function(s) { return s.score > 0; });
    scored.sort(function(a, b) { return b.score - a.score; });
    filteredScripts = scored.map(function(s) { return s.script; });
  }
  activeIndex = 0;
  renderResults();
}

function renderResults() {
  resultsList.innerHTML = '';
  filteredScripts.forEach(function(script, index) {
    var li = document.createElement('li');
    if (index === activeIndex) li.className = 'active';

    var nameSpan = document.createElement('span');
    nameSpan.className = 'script-name';
    nameSpan.textContent = script.name;

    var descSpan = document.createElement('span');
    descSpan.className = 'script-desc';
    descSpan.textContent = script.description;

    li.appendChild(nameSpan);
    li.appendChild(descSpan);

    li.addEventListener('click', function() {
      executeScript(script);
      hidePalette();
    });

    resultsList.appendChild(li);
  });

  var activeEl = resultsList.querySelector('.active');
  if (activeEl) activeEl.scrollIntoView({ block: 'nearest' });
}

// ============================================================
// 8. Event Listeners
// ============================================================

document.addEventListener('keydown', function(e) {
  if ((e.metaKey || e.ctrlKey) && e.key === 'b') {
    e.preventDefault();
    togglePalette();
  }
});

searchInput.addEventListener('input', function() {
  filterScripts(searchInput.value);
});

searchInput.addEventListener('keydown', function(e) {
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    if (activeIndex < filteredScripts.length - 1) {
      activeIndex++;
      renderResults();
    }
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    if (activeIndex > 0) {
      activeIndex--;
      renderResults();
    }
  } else if (e.key === 'Enter') {
    e.preventDefault();
    if (filteredScripts[activeIndex]) {
      executeScript(filteredScripts[activeIndex]);
      hidePalette();
    }
  } else if (e.key === 'Escape') {
    e.preventDefault();
    hidePalette();
  }
});

palette.addEventListener('click', function(e) {
  if (e.target === palette) {
    hidePalette();
  }
});

// ============================================================
// 9. Initialize
// ============================================================

console.log('Flxify loaded: ' + scripts.length + ' scripts available.');

})();
`;

fs.writeFileSync(OUTPUT, output, 'utf-8');
console.log(`Generated app.js (${(output.length / 1024).toFixed(1)} KB)`);
