#!/usr/bin/env node
/**
 * Flxify build script
 *
 * Reads lib modules from web-scripts/lib/, embedded scripts from the
 * SCRIPT_SOURCES in the current app.js, and web scripts from web-scripts/.
 * Generates a fully self-contained app.js that works offline and with file:// URLs.
 *
 * Usage: node build_app.js
 */

const fs = require('fs');
const path = require('path');

const WEB_SCRIPTS_DIR = path.join(__dirname, 'web-scripts');
const LIB_DIR = path.join(WEB_SCRIPTS_DIR, 'lib');
const OUTPUT = path.join(__dirname, 'app.js');

// ---- Lib modules ----
const libFiles = [
  { file: 'base64.js', name: 'base64' },
  { file: 'hashes.js', name: 'hashes' },
  { file: 'he.js', name: 'he' },
  { file: 'js-yaml.js', name: 'js-yaml' },
  { file: 'lodash.boop.js', name: 'lodash.boop' },
  { file: 'papaparse.js', name: 'papaparse' },
  { file: 'vkBeautify.js', name: 'vkBeautify' },
];

// ---- Web-only scripts ----
const webScriptFiles = [
  'UUIDGenerator.js',
  'ExtractURLs.js',
  'ExtractEmails.js',
  'RegexEscape.js',
  'AddLineNumbers.js',
  'RemoveLineNumbers.js',
  'SpacesToTabs.js',
  'TabsToSpaces.js',
];

function escapeForTemplateLiteral(str) {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

// ---- Read lib modules ----
const libEntries = libFiles.map(({ file, name }) => {
  const src = fs.readFileSync(path.join(LIB_DIR, file), 'utf-8');
  return { name, source: escapeForTemplateLiteral(src) };
});

// ---- Read embedded scripts from current app.js ----
// Extract the SCRIPT_SOURCES array content from the existing app.js
const currentAppJs = fs.readFileSync(OUTPUT, 'utf-8');
const sourcesMatch = currentAppJs.match(/const SCRIPT_SOURCES = \[([\s\S]*?)\n\];/);
let embeddedScriptBlock = '';
if (sourcesMatch) {
  embeddedScriptBlock = sourcesMatch[1];
  console.log('Extracted embedded scripts from existing app.js');
} else {
  console.error('Could not find SCRIPT_SOURCES in existing app.js');
  process.exit(1);
}

// ---- Read web scripts ----
const webScriptEntries = webScriptFiles.map(file => {
  const src = fs.readFileSync(path.join(WEB_SCRIPTS_DIR, file), 'utf-8');
  return escapeForTemplateLiteral(src);
});

console.log(`Found ${libEntries.length} lib modules, embedded scripts, and ${webScriptEntries.length} web scripts.`);

// ---- Generate app.js ----
let output = `// Flxify - app.js
// Generated by build_app.js - do not edit directly.
// Edit scripts in web-scripts/ then run: node build_app.js

(function() {
'use strict';

// ============================================================
// 1. Module System (require shim)
// ============================================================

const flxifyModules = {};

function registerModule(name, sourceCode) {
  try {
    const wrappedCode = '(function() {' +
      'var module = { exports: {} };' +
      'var exports = module.exports;' +
      '(function(exports, module) {' +
      sourceCode +
      '}).call(module.exports, module.exports, module);' +
      'return module.exports;' +
      '})()';
    flxifyModules[name] = new Function('return ' + wrappedCode)();
  } catch (e) {
    console.error('Failed to register module: ' + name, e);
  }
}

function require(modulePath) {
  if (typeof modulePath === 'string' && modulePath.startsWith('@flxify/')) {
    const name = modulePath.replace('@flxify/', '').replace('.js', '');
    if (flxifyModules[name]) return flxifyModules[name];
    console.warn('Module not found: ' + name);
  }
  return null;
}

// ============================================================
// 2. Register Lib Modules
// ============================================================

`;

for (const lib of libEntries) {
  output += `registerModule(${JSON.stringify(lib.name)}, \`${lib.source}\`);\n\n`;
}

output += `
// ============================================================
// 3. Script Registry
// ============================================================

const SCRIPT_SOURCES = [
${embeddedScriptBlock}`;

// Add web scripts to the same array
if (webScriptEntries.length > 0) {
  output += `,\n`;
  for (let i = 0; i < webScriptEntries.length; i++) {
    output += `\`${webScriptEntries[i]}\``;
    if (i < webScriptEntries.length - 1) output += ',';
    output += '\n';
  }
}

output += `];

const scripts = [];

function registerScript(source) {
  try {
    const metaMatch = source.match(/\\/\\*\\*([\\s\\S]*?)\\*\\*\\//);
    if (!metaMatch) return;
    const cleanedJson = metaMatch[1].trim().replace(/,\\s*([\\]}])/g, '$1');
    const metadata = JSON.parse(cleanedJson);
    scripts.push({
      name: metadata.name || 'Unnamed',
      description: metadata.description || '',
      author: metadata.author || '',
      icon: metadata.icon || '',
      tags: metadata.tags || '',
      source: source
    });
  } catch (e) {
    console.warn('Failed to parse script metadata:', e);
  }
}

function parseScripts() {
  for (const source of SCRIPT_SOURCES) {
    registerScript(source);
  }
  scripts.sort((a, b) => a.name.localeCompare(b.name));
}

// ============================================================
// 4. Toast System
// ============================================================

function showToast(message, type) {
  const container = document.getElementById('toast');
  const el = document.createElement('div');
  el.className = 'toast-message ' + (type || 'info');
  el.textContent = message;
  container.appendChild(el);
  setTimeout(() => {
    if (el.parentNode) el.parentNode.removeChild(el);
  }, 3000);
}

// ============================================================
// 5. BoopState Class
// ============================================================

class BoopState {
  constructor(fullText, selectionStart, selectionEnd) {
    this._fullText = fullText;
    this._selectionStart = selectionStart;
    this._selectionEnd = selectionEnd;
    this._selection = (selectionStart !== selectionEnd)
      ? fullText.substring(selectionStart, selectionEnd)
      : null;
    this._isSelection = this._selection !== null;
    this._insertText = null;
  }

  get fullText() { return this._fullText; }
  set fullText(val) { this._fullText = val; }

  get selection() { return this._selection; }
  set selection(val) { this._selection = val; }

  get isSelection() { return this._isSelection; }

  get text() {
    return this._isSelection ? this._selection : this._fullText;
  }
  set text(val) {
    if (this._isSelection) {
      this._selection = val;
    } else {
      this._fullText = val;
    }
  }

  postError(msg) { showToast(msg, 'error'); }
  postInfo(msg) { showToast(msg, 'info'); }

  insert(text) {
    this._insertText = text;
  }
}

// ============================================================
// 6. Script Executor
// ============================================================

function executeScript(script) {
  var cm = window.cmEditor;
  var fullText = cm.state.doc.toString();
  var selFrom = cm.state.selection.main.from;
  var selTo = cm.state.selection.main.to;
  var state = new BoopState(fullText, selFrom, selTo);

  try {
    var fn = new Function('require', 'state', script.source + '\\nif (typeof main === "function") main(state);');
    fn(require, state);
  } catch (e) {
    showToast('Error: ' + e.message, 'error');
    console.error('Script execution error:', e);
    return;
  }

  // Apply results back to CodeMirror editor
  if (state._insertText !== null) {
    cm.dispatch({
      changes: { from: selFrom, to: selTo, insert: state._insertText },
      selection: { anchor: selFrom + state._insertText.length }
    });
  } else if (state._isSelection && state._selection !== null) {
    cm.dispatch({
      changes: { from: state._selectionStart, to: state._selectionEnd, insert: state._selection },
      selection: { anchor: state._selectionStart, head: state._selectionStart + state._selection.length }
    });
  } else {
    cm.dispatch({
      changes: { from: 0, to: cm.state.doc.length, insert: state._fullText }
    });
  }
}

// ============================================================
// 7. Command Palette
// ============================================================

const palette = document.getElementById('command-palette');
const searchInput = document.getElementById('search');
const resultsList = document.getElementById('results');
let activeIndex = 0;
let filteredScripts = [];

function showPalette() {
  palette.classList.remove('hidden');
  searchInput.value = '';
  filterScripts('');
  searchInput.focus();
}

function hidePalette() {
  palette.classList.add('hidden');
  if (window.cmEditor) window.cmEditor.focus();
}

function togglePalette() {
  if (palette.classList.contains('hidden')) {
    showPalette();
  } else {
    hidePalette();
  }
}

function fuzzyScore(query, text) {
  if (!query) return 1;
  const lowerQuery = query.toLowerCase();
  const lowerText = text.toLowerCase();

  if (lowerText === lowerQuery) return 100;
  if (lowerText.startsWith(lowerQuery)) return 80;
  if (lowerText.includes(lowerQuery)) return 60;

  let qi = 0;
  let consecutive = 0;
  let maxConsecutive = 0;
  let matched = 0;
  for (let ti = 0; ti < lowerText.length && qi < lowerQuery.length; ti++) {
    if (lowerText[ti] === lowerQuery[qi]) {
      qi++;
      matched++;
      consecutive++;
      if (consecutive > maxConsecutive) maxConsecutive = consecutive;
    } else {
      consecutive = 0;
    }
  }
  if (qi < lowerQuery.length) return 0;
  return 20 + maxConsecutive * 5 + matched;
}

function filterScripts(query) {
  if (!query) {
    filteredScripts = scripts.slice();
  } else {
    const scored = scripts.map(s => {
      const nameScore = fuzzyScore(query, s.name) * 0.9;
      const tagScore = fuzzyScore(query, s.tags) * 0.6;
      const descScore = fuzzyScore(query, s.description) * 0.2;
      const score = Math.max(nameScore, tagScore, descScore);
      return { script: s, score };
    }).filter(s => s.score > 0);
    scored.sort((a, b) => b.score - a.score);
    filteredScripts = scored.map(s => s.script);
  }
  activeIndex = 0;
  renderResults();
}

function renderResults() {
  resultsList.innerHTML = '';
  filteredScripts.forEach((script, index) => {
    const li = document.createElement('li');
    if (index === activeIndex) li.className = 'active';

    const nameSpan = document.createElement('span');
    nameSpan.className = 'script-name';
    nameSpan.textContent = script.name;

    const descSpan = document.createElement('span');
    descSpan.className = 'script-desc';
    descSpan.textContent = script.description;

    li.appendChild(nameSpan);
    li.appendChild(descSpan);

    li.addEventListener('click', () => {
      executeScript(script);
      hidePalette();
    });

    resultsList.appendChild(li);
  });

  const activeEl = resultsList.querySelector('.active');
  if (activeEl) activeEl.scrollIntoView({ block: 'nearest' });
}

// ============================================================
// 8. Event Listeners
// ============================================================

document.addEventListener('keydown', (e) => {
  if ((e.metaKey || e.ctrlKey) && e.key === 'b') {
    e.preventDefault();
    togglePalette();
  }
});

searchInput.addEventListener('input', () => {
  filterScripts(searchInput.value);
});

searchInput.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    if (activeIndex < filteredScripts.length - 1) {
      activeIndex++;
      renderResults();
    }
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    if (activeIndex > 0) {
      activeIndex--;
      renderResults();
    }
  } else if (e.key === 'Enter') {
    e.preventDefault();
    if (filteredScripts[activeIndex]) {
      executeScript(filteredScripts[activeIndex]);
      hidePalette();
    }
  } else if (e.key === 'Escape') {
    e.preventDefault();
    hidePalette();
  }
});

palette.addEventListener('click', (e) => {
  if (e.target === palette) {
    hidePalette();
  }
});

// ============================================================
// 9. Initialize
// ============================================================

parseScripts();
console.log('Flxify loaded: ' + scripts.length + ' scripts available.');

})();
`;

fs.writeFileSync(OUTPUT, output, 'utf-8');
console.log(`Generated app.js (${(output.length / 1024).toFixed(1)} KB)`);
